# Google Cloud Build configuration
# Deploy to Cloud Run with Cloud SQL PostgreSQL

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/iran-protest-map:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/iran-protest-map:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/iran-protest-map:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/iran-protest-map:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iran-protest-map'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iran-protest-map:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},CRON_SECRET=${_CRON_SECRET},REPORT_MAX_AGE_HOURS=168,OPENAI_API_KEY=${_OPENAI_API_KEY},CHECKWX_API_KEY=${_CHECKWX_API_KEY}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

substitutions:
  _REGION: us-central1
  _CLOUD_SQL_INSTANCE: ''  # Set via trigger: PROJECT_ID:REGION:INSTANCE_NAME
  _DATABASE_URL: ''        # Set via trigger or Secret Manager
  _CRON_SECRET: ''         # Set via trigger or Secret Manager
  _OPENAI_API_KEY: ''      # Set via trigger or Secret Manager (for AI summaries)
  _CHECKWX_API_KEY: ''     # Set via trigger or Secret Manager (for NOTAM data)

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/iran-protest-map:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/iran-protest-map:latest'

